name: MeetingTranscriber
options:
  minimumXcodeGenVersion: 2.41.0
  deploymentTarget:
    iOS: '16.0'
settings:
  base:
    SWIFT_VERSION: '5.9'
    DEVELOPMENT_TEAM: ""
    PRODUCT_BUNDLE_IDENTIFIER: com.example.MeetingTranscriber
targets:
  MeetingTranscriber:
    type: application
    platform: iOS
    deploymentTarget: '16.0'
    sources:
      - path: MeetingTranscriber
    settings:
      base:
        INFOPLIST_FILE: MeetingTranscriber/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
    scheme: {}
